org:
  coderclan:
    whistle:
      # Event Queue Size, too small  will cause high latency of delivering,
      # since event faild to put into the queue will not be delivered until the next round of retry.
      #
      # Default value:  128
      eventQueueSize: 32
      table:
        # Database Table name for persisting events
        #
        # Default value: sys_event_out
        producedEvent: sys_persistent_event

logging:
  level:
    org.coderclan: trace

server:
  port: 0
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:whistle-example-producer
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  application:
    name: whistle-example-producer