logging:
  level:
    org:
      coderclan: trace
server:
  port: 0
spring:
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      path: /h2

  cloud:
    stream:
      default:
        consumer:
          concurrency: 1
  datasource:
    url: jdbc:h2:mem:whistle-example-consumer
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  application:
    name: whistle-example-consumer